Repository AY2021S1-CS2103T-T15-3/tp, pull requests merged in 2020-11, with the labels that each got.

#261 Fix suggestion bugs
  src/main/java/seedu/stock/logic/commands/SuggestionCommand.java
  src/main/java/seedu/stock/logic/parser/SuggestionCommandParser.java
  src/test/java/seedu/stock/logic/commands/SuggestionCommandTest.java
  src/test/java/seedu/stock/logic/parser/SuggestionCommandParserTest.java
Labels: type.Bug, type.Task

#264 Enhance existing tests and add new tests
  src/main/java/seedu/stock/logic/commands/CommandWords.java
  src/main/java/seedu/stock/logic/parser/SuggestionCommandParser.java
  src/main/java/seedu/stock/model/stock/QuantityAdder.java
  src/test/java/seedu/stock/logic/commands/SuggestionCommandTest.java
  src/test/java/seedu/stock/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/stock/logic/parser/SuggestionCommandParserTest.java
  src/test/java/seedu/stock/model/ModelManagerTest.java
  src/test/java/seedu/stock/model/stock/QuantityAdderTest.java
  src/test/java/seedu/stock/model/stock/QuantityTest.java
Labels: type.Bug, type.Enhancement

#265 Remove NoteView and implement StockView with Tab
  src/main/java/seedu/stock/logic/commands/CommandResult.java
  src/main/java/seedu/stock/logic/commands/CommandWords.java
  src/main/java/seedu/stock/logic/commands/StockViewCommand.java
  src/main/java/seedu/stock/logic/commands/exceptions/SerialNumberNotFoundException.java
  src/main/java/seedu/stock/logic/parser/StockBookParser.java
  src/main/java/seedu/stock/logic/parser/StockViewCommandParser.java
  src/main/java/seedu/stock/logic/parser/SuggestionCommandParser.java
  src/main/java/seedu/stock/ui/MainWindow.java
  src/main/java/seedu/stock/ui/NoteListPanel.java
  src/main/java/seedu/stock/ui/StockViewCard.java
  src/main/java/seedu/stock/ui/StockViewWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NoteListPanel.fxml
  src/main/resources/view/StockViewCard.fxml
  src/main/resources/view/StockViewWindow.fxml
  src/test/java/seedu/stock/logic/commands/StockViewCommandTest.java
  src/test/java/seedu/stock/logic/parser/StockViewCommandParserTest.java
  src/test/java/seedu/stock/logic/parser/SuggestionCommandParserTest.java
Labels: enhancement

#267 Update ug tutorial for find features
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/clear/clear_step2.png
  docs/images/find/find-step-2-addstocks.png
  docs/images/find/find-step-3.png
  docs/images/find/find-step-4.png
  docs/images/find/find-step-5.png
  docs/images/find/find-step-6.png
  docs/images/find/find-step-7.png
  docs/images/find/findexact-step-3.png
  docs/images/find/findexact-step-4.png
  src/main/java/seedu/stock/logic/parser/NoteCommandParser.java
  src/main/java/seedu/stock/logic/parser/StockBookParser.java
  src/main/java/seedu/stock/ui/StockViewWindow.java
Labels: documentation, type.Task

#272 Update UG documentation
  README.md
  docs/UserGuide.md
  docs/images/note/note-step-1.png
  docs/images/note/note-step-2.png
  docs/images/note/note-step-3.png
  docs/images/note/note-step-4.png
  docs/images/note/note-step-5.png
  docs/images/note/note-step-6.png
  docs/images/note/note-step-7.png
  docs/images/note/note-step-8.png
  docs/images/note/notedelete-step-1.png
  docs/images/note/notedelete-step-2.png
  docs/images/note/notedelete-step-3.png
  docs/images/note/notedelete-step-4.png
  docs/images/note/notedelete-step-5.png
  docs/images/note/notedelete-step-6.png
  docs/images/note/notedelete-step-7.png
  docs/images/note/notedelete-step-8.png
  docs/images/stockview/stockview-step-0.png
  docs/images/stockview/stockview-step-1.png
  docs/images/stockview/stockview-step-2.png
  docs/images/stockview/stockview-step-3-2.png
  docs/images/stockview/stockview-step-3.png
  docs/images/stockview/stockview-step-4-2.png
  docs/images/stockview/stockview-step-4.png
  docs/images/stockview/stockview-step-5.png
  docs/images/stockview/stockview-step-6.png
  docs/images/stockview/stockview-step-7.png
  docs/team/amy.md
  src/main/java/seedu/stock/logic/commands/FindCommand.java
  src/main/java/seedu/stock/logic/commands/FindExactCommand.java
  src/main/java/seedu/stock/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/stock/logic/parser/ParserUtil.java
  src/main/java/seedu/stock/logic/parser/SuggestionCommandParser.java
  src/main/java/seedu/stock/ui/StockViewWindow.java
  src/main/resources/view/StockViewWindow.fxml
  src/test/java/seedu/stock/logic/parser/SuggestionCommandParserTest.java
Labels: documentation

#274 Update DG, UP, PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SortActivityDiagram.puml
  docs/diagrams/SuggestionActivityDiagram.puml
  docs/diagrams/SuggestionSequenceDiagramExample1.puml
  docs/diagrams/SuggestionSequenceDiagramExample2.puml
  docs/diagrams/UpdateActivityDiagram.puml
  docs/diagrams/UpdateSequenceDiagramExample1.puml
  docs/images/SortActivityDiagram.png
  docs/images/SuggestionActivityDiagram.png
  docs/images/SuggestionSequenceDiagramExample1.png
  docs/images/SuggestionSequenceDiagramExample2.png
  docs/images/UpdateActivityDiagram.png
  docs/images/UpdateSequenceDiagramExample1.png
  docs/images/sort/sort_step1.png
  docs/images/sort/sort_step2.png
  docs/images/sort/sort_step3.png
  docs/images/sort/sort_step4.png
  docs/images/sort/sort_step5.png
  docs/images/suggestion/suggestion_step1.png
  docs/images/suggestion/suggestion_step2.png
  docs/images/suggestion/suggestion_step3.png
  docs/images/suggestion/suggestion_step4.png
  docs/images/suggestion/suggestion_step5.png
  docs/images/update/update_step1.png
  docs/images/update/update_step2.png
  docs/images/update/update_step3.png
  docs/images/update/update_step4.png
  docs/images/update/update_step5.png
  docs/images/update/update_step6.png
  docs/team/audrey.md
  docs/team/audreyfelicio.md
  src/main/java/seedu/stock/logic/commands/BookmarkCommand.java
  src/main/java/seedu/stock/logic/commands/UnbookmarkCommand.java
  src/main/java/seedu/stock/logic/commands/UpdateCommand.java
  src/main/java/seedu/stock/logic/parser/SuggestionCommandParser.java
  src/main/java/seedu/stock/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/stock/ui/HelpWindow.java
  src/test/java/seedu/stock/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/stock/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/stock/testutil/UpdateStockDescriptorBuilder.java
Labels: documentation, type.Task

#271 Test_Branch_Dennis
  src/main/java/seedu/stock/logic/commands/BookmarkCommand.java
  src/main/java/seedu/stock/logic/commands/HelpCommand.java
  src/main/java/seedu/stock/logic/commands/UnbookmarkCommand.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/StockListPanel.fxml
  src/test/data/JsonSerializableStockBookTest/typicalStockStockBook.json
  src/test/java/seedu/stock/logic/commands/BookmarkCommandTest.java
  src/test/java/seedu/stock/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/stock/logic/commands/FindCommandTest.java
  src/test/java/seedu/stock/logic/commands/HelpCommandTest.java
  src/test/java/seedu/stock/logic/commands/ListCommandTest.java
  src/test/java/seedu/stock/logic/commands/NoteDeleteCommandTest.java
  src/test/java/seedu/stock/logic/commands/UnbookmarkCommandTest.java
  src/test/java/seedu/stock/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/stock/logic/parser/HelpCommandParserTest.java
  src/test/java/seedu/stock/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/stock/logic/parser/NoteDeleteCommandParserTest.java
  src/test/java/seedu/stock/logic/parser/StockViewCommandParserTest.java
  src/test/java/seedu/stock/testutil/StockBuilder.java
  src/test/java/seedu/stock/testutil/TypicalSerialNumberSets.java
  src/test/java/seedu/stock/testutil/TypicalStocks.java
Labels: type.Task

#281 Ugdg branch dennis
  docs/DeveloperGuide.md
  docs/diagrams/BookmarkCommandActivityDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UnbookmarkCommandActivityDiagram.puml
  docs/images/BookmarkCommandActivityDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UnbookmarkCommandActivityDiagram.png
Labels: documentation, type.Task

#283 Update bookmarkcommand to account for exceptions
  src/main/java/seedu/stock/logic/commands/BookmarkCommand.java
  src/main/java/seedu/stock/logic/commands/UnbookmarkCommand.java
  src/test/java/seedu/stock/logic/commands/BookmarkCommandTest.java
  src/test/java/seedu/stock/logic/commands/ListCommandTest.java
  src/test/java/seedu/stock/logic/commands/UnbookmarkCommandTest.java
Labels: type.Task

#284 Update test cases, UG, DG, Homepage, PPP
  README.md
  build.gradle
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/images/ExpectedHelp.png
  docs/images/sort/sort_step6.png
  docs/images/sort/sort_step7.png
  docs/images/sort/sort_step8.png
  docs/images/update/update_step7.png
  docs/images/update/update_step8.png
  docs/images/update/update_step9.png
  docs/index.md
  docs/team/audreyfelicio.md
  src/main/java/seedu/stock/commons/util/SuggestionUtil.java
  src/main/java/seedu/stock/model/stock/AccumulatedQuantity.java
  src/main/java/seedu/stock/model/stock/Location.java
  src/main/java/seedu/stock/model/stock/Name.java
  src/main/java/seedu/stock/model/stock/Note.java
  src/main/java/seedu/stock/model/stock/NoteIndex.java
  src/main/java/seedu/stock/model/stock/Quantity.java
  src/main/java/seedu/stock/model/stock/SerialNumber.java
  src/main/java/seedu/stock/model/stock/Source.java
  src/test/java/seedu/stock/commons/util/SortUtilTest.java
  src/test/java/seedu/stock/commons/util/SuggestionUtilTest.java
  src/test/java/seedu/stock/logic/commands/CommandTestUtil.java
  src/test/java/seedu/stock/logic/commands/SortCommandTest.java
  src/test/java/seedu/stock/logic/commands/SuggestionCommandTest.java
  src/test/java/seedu/stock/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/stock/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/stock/logic/parser/SuggestionCommandParserTest.java
  src/test/java/seedu/stock/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/stock/model/stock/QuantityAdderTest.java
  src/test/java/seedu/stock/testutil/StockBuilder.java
  src/test/java/seedu/stock/testutil/UpdateStockDescriptorBuilder.java
Labels: documentation, type.Task

#289 Updated PPP, added test cases for sampleutil
  docs/team/ashley-lau.md
  src/main/java/seedu/stock/model/util/SampleDataUtil.java
  src/test/java/seedu/stock/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/stock/logic/commands/AddCommandTest.java
  src/test/java/seedu/stock/model/util/SampleDataUtilTest.java
Labels: type.Task

#290 Clean DG links and add note feature implementation in DG
  docs/DevOps.md
  docs/DeveloperGuide.md
  src/main/java/seedu/stock/ui/MainWindow.java
  src/main/java/seedu/stock/ui/StockCard.java
  src/main/java/seedu/stock/ui/StockViewCard.java
  src/main/java/seedu/stock/ui/StockViewWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StockViewCard.fxml
Labels: documentation

#288 Add logging and assertions to increase defensiveness of code
  src/main/java/seedu/stock/commons/util/SuggestionUtil.java
  src/main/java/seedu/stock/logic/commands/AddCommand.java
  src/main/java/seedu/stock/logic/commands/BookmarkCommand.java
  src/main/java/seedu/stock/logic/commands/ClearCommand.java
  src/main/java/seedu/stock/logic/commands/DeleteCommand.java
  src/main/java/seedu/stock/logic/commands/ExitCommand.java
  src/main/java/seedu/stock/logic/commands/FindCommand.java
  src/main/java/seedu/stock/logic/commands/FindExactCommand.java
  src/main/java/seedu/stock/logic/commands/HelpCommand.java
  src/main/java/seedu/stock/logic/commands/ListAllCommand.java
  src/main/java/seedu/stock/logic/commands/ListBookmarkCommand.java
  src/main/java/seedu/stock/logic/commands/ListLowStocksCommand.java
  src/main/java/seedu/stock/logic/commands/NoteCommand.java
  src/main/java/seedu/stock/logic/commands/NoteDeleteCommand.java
  src/main/java/seedu/stock/logic/commands/PrintCommand.java
  src/main/java/seedu/stock/logic/commands/SortCommand.java
  src/main/java/seedu/stock/logic/commands/SourceQuantityDistributionStatisticsCommand.java
  src/main/java/seedu/stock/logic/commands/SourceStatisticsCommand.java
  src/main/java/seedu/stock/logic/commands/StockViewCommand.java
  src/main/java/seedu/stock/logic/commands/SuggestionCommand.java
  src/main/java/seedu/stock/logic/commands/TabCommand.java
  src/main/java/seedu/stock/logic/commands/UnbookmarkCommand.java
  src/main/java/seedu/stock/logic/commands/UpdateCommand.java
  src/main/java/seedu/stock/logic/parser/AddCommandParser.java
  src/main/java/seedu/stock/logic/parser/BookmarkCommandParser.java
  src/main/java/seedu/stock/logic/parser/ClearCommandParser.java
  src/main/java/seedu/stock/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/stock/logic/parser/ExitCommandParser.java
  src/main/java/seedu/stock/logic/parser/FindCommandParser.java
  src/main/java/seedu/stock/logic/parser/FindExactCommandParser.java
  src/main/java/seedu/stock/logic/parser/HelpCommandParser.java
  src/main/java/seedu/stock/logic/parser/ListCommandParser.java
  src/main/java/seedu/stock/logic/parser/NoteCommandParser.java
  src/main/java/seedu/stock/logic/parser/NoteDeleteCommandParser.java
  src/main/java/seedu/stock/logic/parser/PrintCommandParser.java
  src/main/java/seedu/stock/logic/parser/SortCommandParser.java
  src/main/java/seedu/stock/logic/parser/StatisticsCommandParser.java
  src/main/java/seedu/stock/logic/parser/StockViewCommandParser.java
  src/main/java/seedu/stock/logic/parser/SuggestionCommandParser.java
  src/main/java/seedu/stock/logic/parser/TabCommandParser.java
  src/main/java/seedu/stock/logic/parser/UnbookmarkCommandParser.java
  src/main/java/seedu/stock/logic/parser/UpdateCommandParser.java
Labels: type.Enhancement, type.Task

#293 Update DG, PPP, Effort
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/audreyfelicio.md
Labels: documentation, type.Task

#294 Add stockview implementation to DG
  docs/DeveloperGuide.md
  docs/diagrams/FindFeatureSequenceDiagram.puml
  docs/diagrams/NoteFeatureActivityDiagram.puml
  docs/diagrams/NoteFeatureSequenceDiagram.puml
  docs/diagrams/StockViewActivityDiagram.puml
  docs/diagrams/StockViewLogicSequenceDiagram.puml
  docs/diagrams/StockViewUISequenceDiagram.puml
  docs/images/NoteFeatureActivityDiagram.png
  docs/images/NoteFeatureSequenceDiagram.png
  docs/images/StockViewActivityDiagram.png
  docs/images/StockViewLogicSequenceDiagram.png
  docs/images/StockViewUISequenceDiagram.png
  src/main/java/seedu/stock/logic/commands/CommandResult.java
  src/main/java/seedu/stock/logic/commands/NoteCommand.java
  src/main/java/seedu/stock/logic/commands/NoteDeleteCommand.java
  src/main/java/seedu/stock/logic/commands/StockViewCommand.java
  src/main/java/seedu/stock/ui/MainWindow.java
Labels: documentation

#297 Update PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/amy.md
  docs/team/amylzting.md
Labels: documentation

#302 Improve on documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ashley-lau.md
  src/test/java/seedu/stock/logic/commands/AddCommandTest.java
  src/test/java/seedu/stock/logic/commands/BookmarkCommandTest.java
  src/test/java/seedu/stock/logic/commands/PrintCommandTest.java
Labels: documentation

#307 Update UG on bookmarking multiple
  docs/UserGuide.md
  docs/images/bookmark/bookmark_multiple.png
  docs/images/bookmark/bookmark_multiple_before.png
  docs/images/bookmark/unbookmark_multiple.png
  docs/images/bookmark/unbookmark_multiple_before.png
Labels: documentation, type.Task

#301 Configure codecov and refine PPP
  README.md
  codecov.yml
  docs/UserGuide.md
  docs/index.md
  docs/team/audreyfelicio.md
Labels: type.Enhancement, type.Task

#308 Fix documentation and abstract code
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ArchitectureSequenceDiagram.png
  docs/team/amylzting.md
  src/main/java/seedu/stock/logic/parser/FindCommandParser.java
  src/main/java/seedu/stock/logic/parser/FindExactCommandParser.java
  src/main/java/seedu/stock/logic/parser/NoteCommandParser.java
  src/main/java/seedu/stock/logic/parser/NoteDeleteCommandParser.java
  src/main/java/seedu/stock/logic/parser/ParserUtil.java
  src/main/java/seedu/stock/logic/parser/StockViewCommandParser.java
  src/main/java/seedu/stock/ui/MainWindow.java
Labels: documentation

#313 Add update stock descriptor test
  docs/team/audreyfelicio.md
  src/main/java/seedu/stock/logic/commands/UpdateCommand.java
  src/test/java/seedu/stock/logic/commands/CommandTestUtil.java
  src/test/java/seedu/stock/logic/commands/EditStockDescriptorTest.java
  src/test/java/seedu/stock/logic/commands/UpdateStockDescriptorTest.java
  src/test/java/seedu/stock/logic/parser/StockBookParserTest.java
  src/test/java/seedu/stock/logic/parser/UpdateCommandParserTest.java
Labels: type.Task

#343 Add ParserUtil tests
  README.md
  docs/team/amylzting.md
  src/main/java/seedu/stock/logic/parser/ParserUtil.java
  src/test/java/seedu/stock/logic/parser/ParserUtilTest.java
  src/test/java/seedu/stock/testutil/TypicalStocks.java
Labels: documentation, type.Task

#345 Update typos
  docs/UserGuide.md
Labels: documentation, type.Task

#347 Update DG for bookmark and unbookmark manual testing
  docs/DeveloperGuide.md
Labels: documentation, type.Task

#344 Fix DG, UG, Help window
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/LogicListAllSequenceDiagram.puml
  docs/diagrams/UpdateSequenceDiagramExample1.puml
  docs/images/LogicListAllSequenceDiagram.png
  docs/images/UpdateSequenceDiagramExample1.png
  docs/index.md
  docs/team/audreyfelicio.md
  src/main/java/seedu/stock/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: documentation, type.Task

#354 Branch ashley documentation
  docs/UserGuide.md
  docs/images/addStockExample3.png
  docs/images/addStockExample4.png
  docs/images/addStockExample5.png
  docs/images/addStockExample6.png
  docs/images/addStockExample7.png
Labels: documentation, type.Task

#359 Shorten PPP
  build.gradle
  docs/UserGuide.md
  docs/index.md
  docs/team/audreyfelicio.md
Labels: documentation, type.Task

#362 Add comments to adhere to reuse policy
  src/main/java/seedu/stock/commons/util/SuggestionUtil.java
Labels: type.Task
