Repository AY2021S1-CS2103T-T15-3/tp, pull requests merged in 2020-10, with the labels that each got.

#92 Add SerialNumber parser
  src/main/java/seedu/stock/logic/parser/ParserUtil.java
  src/main/java/seedu/stock/model/stock/SerialNumber.java
  src/main/java/seedu/stock/model/stock/Source.java
Labels: enhancement

#93 Add Find stocks command for Warenager
  src/main/java/seedu/stock/logic/commands/FindCommand.java
  src/main/java/seedu/stock/logic/parser/CliSyntax.java
  src/main/java/seedu/stock/logic/parser/FindCommandParser.java
  src/main/java/seedu/stock/logic/parser/StockBookParser.java
  src/main/java/seedu/stock/model/stock/predicates/LocationContainsKeywordsPredicate.java
  src/main/java/seedu/stock/model/stock/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/stock/model/stock/predicates/SerialNumberContainsKeywordsPredicate.java
  src/main/java/seedu/stock/model/stock/predicates/SourceContainsKeywordsPredicate.java
  src/main/java/seedu/stock/ui/StockListPanel.java
Labels: type.Task

#94 Kaichao delete feature
  src/main/java/seedu/stock/commons/core/Messages.java
  src/main/java/seedu/stock/logic/commands/DeleteCommand.java
  src/main/java/seedu/stock/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/stock/logic/parser/ParserUtil.java
  src/main/java/seedu/stock/logic/parser/StockBookParser.java
  src/main/java/seedu/stock/model/Model.java
  src/main/java/seedu/stock/model/ModelManager.java
  src/main/java/seedu/stock/model/stock/SerialNumber.java
  src/main/java/seedu/stock/model/stock/predicates/SerialNumberContainsKeywordsPredicate.java
  src/main/java/seedu/stock/storage/JsonAdaptedStock.java
  src/main/java/seedu/stock/ui/StockCard.java
Labels: priority.High, priority.Medium

#105 Kaichao update DG
  docs/DeveloperGuide.md
  docs/team/kaichao.md
Labels: documentation

#101 Implement Update Functionality
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/stock/logic/commands/UpdateCommand.java
  src/main/java/seedu/stock/logic/parser/CliSyntax.java
  src/main/java/seedu/stock/logic/parser/ParserUtil.java
  src/main/java/seedu/stock/logic/parser/StockBookParser.java
  src/main/java/seedu/stock/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/stock/model/Model.java
  src/main/java/seedu/stock/model/ModelManager.java
  src/main/java/seedu/stock/model/StockBook.java
  src/main/java/seedu/stock/model/stock/Quantity.java
  src/main/java/seedu/stock/model/stock/QuantityAdder.java
  src/main/java/seedu/stock/model/stock/UniqueStockList.java
Labels: type.Task

#111 Update UG for find feature
  docs/UserGuide.md
Labels: documentation, type.Task

#118 Add JUnit Tests for DeleteCommand
  src/main/java/seedu/stock/commons/core/Messages.java
  src/main/java/seedu/stock/logic/commands/DeleteCommand.java
  src/main/java/seedu/stock/logic/parser/ParserUtil.java
  src/test/java/seedu/stock/logic/commands/CommandTestUtil.java
  src/test/java/seedu/stock/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/stock/testutil/TestUtil.java
  src/test/java/seedu/stock/testutil/TypicalIndexes.java
  src/test/java/seedu/stock/testutil/TypicalStocks.java
Labels: priority.Medium

#120 Update UG for FindExact feature
  docs/UserGuide.md
Labels: documentation, type.Task

#122 Update find feature parser and predicates
  src/main/java/seedu/stock/logic/parser/FindCommandParser.java
  src/main/java/seedu/stock/model/stock/predicates/LocationContainsKeywordsPredicate.java
  src/main/java/seedu/stock/model/stock/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/stock/model/stock/predicates/SerialNumberContainsKeywordsPredicate.java
  src/main/java/seedu/stock/model/stock/predicates/SourceContainsKeywordsPredicate.java
  src/main/java/seedu/stock/ui/HelpWindow.java
  src/test/java/seedu/stock/model/stock/predicates/NameContainsKeywordsPredicateTest.java
Labels: enhancement

#121 Update docs for update feature and fix formatting errors
  build.gradle
  docs/AboutUs.md
  docs/UserGuide.md
  docs/_config.yml
  docs/team/audrey.md
Labels: documentation

#127 Add tests for field predicates for find features
  src/test/java/seedu/stock/model/stock/predicates/LocationContainsKeywordsPredicateTest.java
  src/test/java/seedu/stock/model/stock/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/stock/model/stock/predicates/SerialNumberContainsKeywordsPredicateTest.java
  src/test/java/seedu/stock/model/stock/predicates/SourceContainsKeywordsPredicateTest.java
Labels: priority.Medium, type.Task

#129 Add tests for find command
  src/test/java/seedu/stock/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/stock/logic/commands/FindCommandTest.java
  src/test/java/seedu/stock/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/stock/testutil/TypicalStocks.java
Labels: priority.Medium, type.Task

#145 Add suggestion feature to UG and DG and fix bugs in suggestion feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SuggestionActivityDiagram.puml
  docs/diagrams/SuggestionSequenceDiagramExample1.puml
  docs/diagrams/SuggestionSequenceDiagramExample2.puml
  docs/images/SuggestionActivityDiagram.png
  docs/images/SuggestionSequenceDiagramExample1.png
  docs/images/SuggestionSequenceDiagramExample2.png
  src/main/java/seedu/stock/logic/parser/CliSyntax.java
  src/main/java/seedu/stock/logic/parser/SuggestionCommandParser.java
Labels: documentation, type.Task

#147 Implement optional notes feature
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/amy.md
  docs/team/ashley.md
  docs/team/kaichao.md
  src/main/java/seedu/stock/logic/commands/CommandWords.java
  src/main/java/seedu/stock/logic/commands/FindCommand.java
  src/main/java/seedu/stock/logic/commands/FindExactCommand.java
  src/main/java/seedu/stock/logic/commands/NoteCommand.java
  src/main/java/seedu/stock/logic/commands/NoteDeleteCommand.java
  src/main/java/seedu/stock/logic/commands/UpdateCommand.java
  src/main/java/seedu/stock/logic/parser/CliSyntax.java
  src/main/java/seedu/stock/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/stock/logic/parser/DeleteNoteCommandParser.java
  src/main/java/seedu/stock/logic/parser/FindCommandParser.java
  src/main/java/seedu/stock/logic/parser/FindExactCommandParser.java
  src/main/java/seedu/stock/logic/parser/NoteCommandParser.java
  src/main/java/seedu/stock/logic/parser/ParserUtil.java
  src/main/java/seedu/stock/logic/parser/StockBookParser.java
  src/main/java/seedu/stock/logic/parser/SuggestionCommandParser.java
  src/main/java/seedu/stock/model/stock/AccumulatedQuantity.java
  src/main/java/seedu/stock/model/stock/Location.java
  src/main/java/seedu/stock/model/stock/Note.java
  src/main/java/seedu/stock/model/stock/Quantity.java
  src/main/java/seedu/stock/model/stock/QuantityAdder.java
  src/main/java/seedu/stock/model/stock/Source.java
  src/main/java/seedu/stock/model/stock/Stock.java
  src/main/java/seedu/stock/storage/JsonAdaptedStock.java
  src/main/java/seedu/stock/ui/StockCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StockListCard.fxml
Labels: type.Task

#154 Update UG and DG for note feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/add_note1_to_banana.png
  docs/images/add_note1_to_stock.png
  docs/images/add_note2_to_stock.png
  docs/images/after_note_delete_0.png
  docs/images/after_note_delete_1.png
  docs/team/amy.md
  src/main/java/seedu/stock/logic/commands/NoteDeleteCommand.java
Labels: documentation, type.Task

#151 Implement sort feature
  src/main/java/seedu/stock/commons/util/SortUtil.java
  src/main/java/seedu/stock/logic/commands/CommandWords.java
  src/main/java/seedu/stock/logic/commands/SortCommand.java
  src/main/java/seedu/stock/logic/parser/CliSyntax.java
  src/main/java/seedu/stock/logic/parser/SortCommandParser.java
  src/main/java/seedu/stock/logic/parser/StockBookParser.java
  src/main/java/seedu/stock/logic/parser/SuggestionCommandParser.java
  src/main/java/seedu/stock/model/Model.java
  src/main/java/seedu/stock/model/ModelManager.java
  src/main/java/seedu/stock/model/StockBook.java
  src/main/java/seedu/stock/model/stock/UniqueStockList.java
  src/test/java/seedu/stock/logic/commands/AddCommandTest.java
Labels: type.Task

#163 Add Find Feature Implementation in DG
  docs/DeveloperGuide.md
Labels: documentation

#165 Update DG diagrams and find feature implementation
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/FindFeatureActivityDiagram.puml
  docs/diagrams/FindFeatureSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/FindFeatureActivityDiagram.png
  docs/images/FindFeatureSequenceDiagram.png
  src/main/java/seedu/stock/logic/parser/FindCommandParser.java
  src/main/java/seedu/stock/logic/parser/FindExactCommandParser.java
Labels: documentation

#169 Update UG
  docs/UserGuide.md
  docs/images/stockCsvExample1.png
  docs/images/stockCsvExample2.png
  docs/images/stockCsvExample3.png
Labels: documentation

#167 Clean, format and update UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/stock/logic/commands/StatisticsCommand.java
Labels: documentation

#171 Fix UG
  docs/UserGuide.md
Labels: documentation

#170 Fix formatting issues
  docs/UserGuide.md
Labels: documentation

#177 Add functionality to view notes
  src/main/java/seedu/stock/logic/commands/BookmarkCommand.java
  src/main/java/seedu/stock/logic/commands/CommandResult.java
  src/main/java/seedu/stock/logic/commands/CommandWords.java
  src/main/java/seedu/stock/logic/commands/ExitCommand.java
  src/main/java/seedu/stock/logic/commands/HelpCommand.java
  src/main/java/seedu/stock/logic/commands/ListBookmarkCommand.java
  src/main/java/seedu/stock/logic/commands/ListCommand.java
  src/main/java/seedu/stock/logic/commands/ListLowStocksCommand.java
  src/main/java/seedu/stock/logic/commands/NoteCommand.java
  src/main/java/seedu/stock/logic/commands/NoteDeleteCommand.java
  src/main/java/seedu/stock/logic/commands/NoteViewCommand.java
  src/main/java/seedu/stock/logic/commands/SourceQuantityDistributionStatisticsCommand.java
  src/main/java/seedu/stock/logic/commands/SourceStatisticsCommand.java
  src/main/java/seedu/stock/logic/commands/SuggestionCommand.java
  src/main/java/seedu/stock/logic/commands/UnbookmarkCommand.java
  src/main/java/seedu/stock/logic/commands/UpdateCommand.java
  src/main/java/seedu/stock/logic/parser/NoteDeleteCommandParser.java
  src/main/java/seedu/stock/logic/parser/NoteViewCommandParser.java
  src/main/java/seedu/stock/logic/parser/StockBookParser.java
  src/main/java/seedu/stock/logic/parser/SuggestionCommandParser.java
  src/main/java/seedu/stock/model/Model.java
  src/main/java/seedu/stock/model/ModelManager.java
  src/main/java/seedu/stock/ui/MainWindow.java
  src/main/java/seedu/stock/ui/NoteCard.java
  src/main/java/seedu/stock/ui/NoteListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/NoteListCard.fxml
  src/main/resources/view/NoteListPanel.fxml
Labels: enhancement

#208 Update UG note feature screenshots
  docs/UserGuide.md
  docs/images/note_img1.jpg
  docs/images/note_img2.jpg
  docs/images/note_img3.jpg
  docs/images/notedelete_img1.jpg
  docs/images/notedelete_img2.jpg
Labels: documentation

#209 Update sort feature UG pictures
  docs/UserGuide.md
  docs/images/SortNameAscending.png
  docs/images/SortQuantityDescending.png
Labels: documentation, type.Task

#212 Branch amy update ug dg
  docs/UserGuide.md
  docs/images/noteview_img1.jpg
  docs/images/noteview_img2.jpg
Labels: documentation

#218 Fix bug of note and bookmark
  src/main/java/seedu/stock/logic/commands/UpdateCommand.java
  src/main/java/seedu/stock/model/stock/Stock.java
Labels: bug

#219 Fix help window and add missing commands
  src/main/java/seedu/stock/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task

#221 Add diagrams to logic architecture
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/LogicListAllSequenceDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/LogicListAllSequenceDiagram.png
  docs/index.md
Labels: type.Task

#222 Enhance update feature, fix bugs, and improve error handling
  src/main/java/seedu/stock/logic/commands/UpdateCommand.java
  src/main/java/seedu/stock/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/stock/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/stock/logic/parser/ParserUtil.java
  src/main/java/seedu/stock/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/stock/model/stock/Quantity.java
  src/main/java/seedu/stock/model/stock/QuantityAdder.java
Labels: enhancement, type.Bug, type.Task

#252 Standardize format for commands
  docs/UserGuide.md
  src/main/java/seedu/stock/logic/commands/AddCommand.java
  src/main/java/seedu/stock/logic/commands/BookmarkCommand.java
  src/main/java/seedu/stock/logic/commands/ClearCommand.java
  src/main/java/seedu/stock/logic/commands/DeleteCommand.java
  src/main/java/seedu/stock/logic/commands/ExitCommand.java
  src/main/java/seedu/stock/logic/commands/FindCommand.java
  src/main/java/seedu/stock/logic/commands/FindExactCommand.java
  src/main/java/seedu/stock/logic/commands/HelpCommand.java
  src/main/java/seedu/stock/logic/commands/ListCommand.java
  src/main/java/seedu/stock/logic/commands/NoteCommand.java
  src/main/java/seedu/stock/logic/commands/NoteDeleteCommand.java
  src/main/java/seedu/stock/logic/commands/NoteViewCommand.java
  src/main/java/seedu/stock/logic/commands/PrintCommand.java
  src/main/java/seedu/stock/logic/commands/SortCommand.java
  src/main/java/seedu/stock/logic/commands/StatisticsCommand.java
  src/main/java/seedu/stock/logic/commands/UnbookmarkCommand.java
  src/main/java/seedu/stock/logic/commands/UpdateCommand.java
  src/main/java/seedu/stock/ui/HelpWindow.java
Labels: documentation, type.Task

#253 Add note command tests
  src/main/java/seedu/stock/logic/Logic.java
  src/main/java/seedu/stock/logic/LogicManager.java
  src/main/java/seedu/stock/logic/commands/Command.java
  src/main/java/seedu/stock/logic/commands/NoteCommand.java
  src/main/java/seedu/stock/logic/commands/NoteDeleteCommand.java
  src/main/java/seedu/stock/logic/commands/exceptions/SerialNumberNotFoundException.java
  src/main/java/seedu/stock/logic/commands/exceptions/SourceCompanyNotFoundException.java
  src/main/java/seedu/stock/model/stock/AccumulatedQuantity.java
  src/main/java/seedu/stock/model/stock/Location.java
  src/main/java/seedu/stock/model/stock/Name.java
  src/main/java/seedu/stock/model/stock/Note.java
  src/main/java/seedu/stock/model/stock/Quantity.java
  src/main/java/seedu/stock/model/stock/QuantityAdder.java
  src/main/java/seedu/stock/model/stock/SerialNumber.java
  src/main/java/seedu/stock/model/stock/SerialNumberSet.java
  src/main/java/seedu/stock/model/stock/Source.java
  src/main/java/seedu/stock/model/stock/Stock.java
  src/main/java/seedu/stock/ui/CommandBox.java
  src/main/java/seedu/stock/ui/MainWindow.java
  src/test/java/seedu/stock/logic/commands/CommandTestUtil.java
  src/test/java/seedu/stock/logic/commands/NoteCommandTest.java
  src/test/java/seedu/stock/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/stock/testutil/StockBuilder.java
  src/test/java/seedu/stock/testutil/TypicalStocks.java
Labels: type.Task

#254 Fix broken update tests
  src/test/java/seedu/stock/logic/commands/UpdateCommandTest.java
Labels: type.Task
